In [1]:
print("hello World")

hello World


# Welcome to Python workshop
## Hello
Cell type code to Markdown - ESC + M  Then shift Enter
Markdown to code - ESC+Y , then shift enter

In [3]:
!dir

 Volume in drive D is LENOVO
 Volume Serial Number is 0299-ED51

 Directory of D:\handson

30-06-2021  14:01    <DIR>          .
30-06-2021  14:01    <DIR>          ..
30-06-2021  13:53    <DIR>          .ipynb_checkpoints
30-06-2021  12:57           138,062 air_quality_no2_long.csv
29-06-2021  13:36    <DIR>          data
28-06-2021  21:14    <DIR>          DAY1
28-06-2021  21:13            43,208 DAY1.txt
29-06-2021  21:34    <DIR>          DAY2
29-06-2021  20:22            22,020 DAY2.txt
30-06-2021  04:31    <DIR>          DAY3
30-06-2021  11:25                 0 DAY3.txt
30-06-2021  13:35    <DIR>          demo_code
29-06-2021  10:17            94,208 fake.db
30-06-2021  14:01             1,058 first.ipynb
30-06-2021  12:29            31,903 pandas_flask_handson.zip
30-06-2021  06:31             1,811 quick_server.py
30-06-2021  06:26    <DIR>          templates
30-06-2021  13:53                72 Untitled.ipynb
               9 File(s)        332,342 bytes
               9 Dir(s)

In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [5]:
%pwd

'D:\\handson'

In [6]:
%%html
<html>
<body>
<table>
        <tr> 
            <th>Name</th> 
            <th>Country</th> 
            <th>Age</th> 
        </tr> 
        <tr> 
            <td>Sid</td> 
            <td>India</td> 
            <td>22</td> 
        </tr>
        <tr> 
            <td>Dave</td> 
            <td>UK</td> 
            <td>28</td> 
        </tr>
</table>
</body>
</html>

# Numpy

In [7]:
n = 100000
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [8]:
import random
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [9]:
x[:3], y[:3]

([0.13976017442629507, 0.8745372323020862, 0.6322788950831936],
 [0.03741630741644375, 0.6527285671947904, 0.5647491021835306])

In [10]:
%timeit [x[i]+y[i] for i in range(n)]

29.5 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
xa = np.array(x)
ya = np.array(y)

In [12]:
%timeit xa+ya

197 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# numpy operations

https://numpy.org/doc/stable/reference/

In [13]:
len(dir(np))

620

In [14]:
x = np.array([1,3,4])
y = np.linspace(2., 3., num=3)
z = np.arange(12).reshape(2,6)
ru =np.random.random((2,6))
rn = np.random.normal( 0,1, (6,4)) # mu, sigma

In [17]:
print(f"x={x}\ny={y}\nz={z}\nru={ru}\nrn={rn}")

x=[1 3 4]
y=[2.  2.5 3. ]
z=[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
ru=[[0.2757758  0.92187527 0.38649672 0.40621038 0.37901984 0.88919691]
 [0.45234151 0.67567794 0.02075717 0.04432555 0.06146123 0.01938419]]
rn=[[ 1.56004153e+00 -1.00444935e+00 -3.69884849e-01 -7.98369755e-01]
 [ 7.66051075e-02  4.85110290e-01  1.06412344e+00  2.88277152e-01]
 [-7.16275977e-01  8.90482063e-03 -9.57403093e-01  1.74682488e+00]
 [ 3.72121528e-01  3.19433263e-01 -4.69647353e-04 -4.70615053e-01]
 [ 9.48809738e-01 -5.02499530e-01 -5.97861809e-01  5.65978566e-01]
 [ 7.76076663e-01  1.03272781e-02  3.12371132e-01  1.44423930e-01]]


In [19]:
# metadata
x.shape
x.ndim
z.shape

(2, 6)

In [18]:
ru.ndim

2

In [20]:
x[0], z[0,0],z[:,0:2]

(1, 0, array([[0, 1],
        [6, 7]]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [21]:
 z[z>2], z[(z>2)&(z<4)]#and-&, or-|, not-~

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]), array([3]))

In [22]:
#how to convert 1D to 2D
y.shape

(3,)

In [24]:
y1 = y[:, None]

In [26]:
y1, y1.shape

(array([[2. ],
        [2.5],
        [3. ]]), (3, 1))

## Broadcasting rule
1. Shape manipulation 
   Convert lower rank array's shape to higher rank shape 
   'by prepending 1'(always prepend)
   For example vector with shape (3,) 
   is converted to rank 2 array as (1,3) or rank 3 as (1,1,3)
   array with (2,3) is converted to rank 3 by (1,2,3)
						
2. Compatibility of arrays 
   Compatible if they have the same size in a dimension, 
   or if one of the arrays has size 1 in that dimension.
   For example , shape (2,3) is compatible with other array 
   with shape (2,3) or (1,3) or (2,1) or (1,1) or (1,) 
   then Broadcasting is possible for other array  

3. Broadcasting  
   If a dimesion is 1 , other dimesions are copied along that dimension 
   when doing operations between arrays 
   eg (1,3) is stacked(vert) 2 times to get (2,3) ie np.tile(x13,(2,1)) #(row_times, col_times)
   (2,1) is stacked three times(horz) to get (2,3) ie  np.tile(x21, (1,3)) or np.repeat(x21, 3, axis=1) 
   (1,1) or (1,) can be tiled ie np.tile(x11, (2,3))
   #Example:
   If a.shape is (5,1), b.shape is (1,6), c.shape is (6,) 
   and d.shape is () (ie d scalar), 
   then a, b, c, and d are all broadcastable to dimension (5,6); 
    •a acts like a (5,6) array where a[:,0] is broadcast to the other columns,
    •b acts like a (5,6) array where b[0,:] is broadcast to the other rows,
    •c acts like a (1,6) array and therefore like a (5,6) array where c[:] is broadcast to every row
    •d acts like a (5,6) array where the single value is repeated.

In [27]:
x.shape, y1.shape

((3,), (3, 1))