In [1]:
print("hello World")

hello World


# Welcome to Python workshop
## Hello
Cell type code to Markdown - ESC + M  Then shift Enter
Markdown to code - ESC+Y , then shift enter

In [3]:
!dir

 Volume in drive D is LENOVO
 Volume Serial Number is 0299-ED51

 Directory of D:\handson

30-06-2021  14:01    <DIR>          .
30-06-2021  14:01    <DIR>          ..
30-06-2021  13:53    <DIR>          .ipynb_checkpoints
30-06-2021  12:57           138,062 air_quality_no2_long.csv
29-06-2021  13:36    <DIR>          data
28-06-2021  21:14    <DIR>          DAY1
28-06-2021  21:13            43,208 DAY1.txt
29-06-2021  21:34    <DIR>          DAY2
29-06-2021  20:22            22,020 DAY2.txt
30-06-2021  04:31    <DIR>          DAY3
30-06-2021  11:25                 0 DAY3.txt
30-06-2021  13:35    <DIR>          demo_code
29-06-2021  10:17            94,208 fake.db
30-06-2021  14:01             1,058 first.ipynb
30-06-2021  12:29            31,903 pandas_flask_handson.zip
30-06-2021  06:31             1,811 quick_server.py
30-06-2021  06:26    <DIR>          templates
30-06-2021  13:53                72 Untitled.ipynb
               9 File(s)        332,342 bytes
               9 Dir(s)

In [4]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%py

In [5]:
%pwd

'D:\\handson'

In [6]:
%%html
<html>
<body>
<table>
        <tr> 
            <th>Name</th> 
            <th>Country</th> 
            <th>Age</th> 
        </tr> 
        <tr> 
            <td>Sid</td> 
            <td>India</td> 
            <td>22</td> 
        </tr>
        <tr> 
            <td>Dave</td> 
            <td>UK</td> 
            <td>28</td> 
        </tr>
</table>
</body>
</html>

# Numpy

In [7]:
n = 100000
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [8]:
import random
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [9]:
x[:3], y[:3]

([0.13976017442629507, 0.8745372323020862, 0.6322788950831936],
 [0.03741630741644375, 0.6527285671947904, 0.5647491021835306])

In [10]:
%timeit [x[i]+y[i] for i in range(n)]

29.5 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
xa = np.array(x)
ya = np.array(y)

In [12]:
%timeit xa+ya

197 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# numpy operations

https://numpy.org/doc/stable/reference/

In [13]:
len(dir(np))

620

In [14]:
x = np.array([1,3,4])
y = np.linspace(2., 3., num=3)
z = np.arange(12).reshape(2,6)
ru =np.random.random((2,6))
rn = np.random.normal( 0,1, (6,4)) # mu, sigma

In [17]:
print(f"x={x}\ny={y}\nz={z}\nru={ru}\nrn={rn}")

x=[1 3 4]
y=[2.  2.5 3. ]
z=[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
ru=[[0.2757758  0.92187527 0.38649672 0.40621038 0.37901984 0.88919691]
 [0.45234151 0.67567794 0.02075717 0.04432555 0.06146123 0.01938419]]
rn=[[ 1.56004153e+00 -1.00444935e+00 -3.69884849e-01 -7.98369755e-01]
 [ 7.66051075e-02  4.85110290e-01  1.06412344e+00  2.88277152e-01]
 [-7.16275977e-01  8.90482063e-03 -9.57403093e-01  1.74682488e+00]
 [ 3.72121528e-01  3.19433263e-01 -4.69647353e-04 -4.70615053e-01]
 [ 9.48809738e-01 -5.02499530e-01 -5.97861809e-01  5.65978566e-01]
 [ 7.76076663e-01  1.03272781e-02  3.12371132e-01  1.44423930e-01]]
